name: Python package

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      with:
        version: 0.12.24
    - name: Build sdist and wheel
      run: uv run --python 3.14 ./run build --verbose
    - name: Upload packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: dist
        path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Download packages
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: dist
        path: dist/
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      with:
        version: 0.12.24
    - name: Install package and run tests
      run: |
        echo "$ uv venv --python ${{ matrix.python-version }} .venv"
        uv venv --python ${{ matrix.python-version }} .venv
        echo ""
        echo "$ source .venv/bin/activate"
        source .venv/bin/activate
        echo ""
        echo "$ uv pip install dist/*.whl"
        uv pip install dist/*.whl
        echo ""
        echo "$ ./run tests --verbose"
        ./run tests --verbose

  presubmit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      with:
        version: 0.12.24
    - name: Run presubmit
      run: |
        uv run --python ${{ matrix.python-version }} ./run presubmit --verbose
