name: Python package

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: 0.12.24
    - name: Build sdist and wheel
      run: uv run --python 3.14 ./run build --verbose
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: astral-sh/setup-uv@v7
        with:
          version: 0.12.24
      - name: Install wheel and run tests
        run: |
          echo "# uv venv --python ${{ matrix.python-version }} .venv"
          uv venv --python ${{ matrix.python-version }} .venv
          echo ""
          echo "source .venv/bin/activate"
          source .venv/bin/activate
          echo ""
          echo "uv pip install dist/*.whl"
          uv pip install dist/*.whl
          echo ""
          echo "./run tests --verbose"
          ./run tests --verbose


  presubmit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: 0.12.24
    - name: Run presubmit
      run: uv run --python ${{ matrix.python-version }} ./run presubmit --verbose
